backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "panels"
    label: "FF Panels"
    folder: "content/panels"
    create: true
    delete: true # এটি আগের পোস্ট ডিলিট করার বাটন দিবে
    format: "json"
    slug: "{{title}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Thumbnail Image", name: "thumbnail", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Download Link", name: "download_link", widget: "string"}
